version: '3.8'
services:
  tdbserver:
    image: rc2server/dbserver:latest
    ports:
      - "5434:5432"
    volumes:
      - rc2Tdbdata:/rc2/rc2dbdata
  tcompute:
    command: ["/rc2compute/wsserver"]
    image: rc2server/compute:0.8.2
    cap_add:
     - SYS_PTRACE
    security_opt:
     - seccomp:unconfined
    ports:
      - "7714:7714"
      - "10000-11000:10000-11000"
    volumes:
      - rc2Tcomputelocal:/rc2compute/userlib
    environment:
      RC2_LOG_JSON_OUT: 1
    depends_on:
      - tdbserver
volumes:
  rc2Tdbdata:
  rc2Tcomputelocal:
