apiVersion: apps/v1
kind: Deployment
metadata:
  name: appserver-deployment
spec:
  selector:
    matchLabels:
      app: appserver
  replicas: 1
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
        - image: docker.io/rc2server/appserver:0.6.6
          name: rc2appserver
          command: [ "/rc2/appserver", "-D", "/rc2/config" ]
          ports:
          - containerPort: 8088
          volumeMounts:
          - name: app-config-volume
            mountPath: /rc2/config
      volumes:
        - name: app-config-volume
          configMap:
            name: appserver-release
