apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: appserver-release
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.rc2.io
      http:
        paths:
          - path: /
            backend:
              serviceName: appserver-service
              servicePort: 80
  tls:
    - hosts:
        - api.rc2.io
      secretName: api-rc2-io-tls
