apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: appserver-release
  annotations:
#    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: rc2api-ip
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: api.rc2.io
      http:
        paths:
          - path: /
            backend:
              serviceName: appserver
              servicePort: 80
          - path: /dev
            backend:
              serviceName: appserver-dev
              servicePort: 80
  tls:
    - hosts:
        - api.rc2.io
      secretName: api-rc2-io-tls
