apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rc2ing
  annotations:
#    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: rc2api-ip
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - secretName: api-rc2-io-tls
#  tls:
#    - hosts:
#        - api.rc2.io
#      secretName: api-rc2-io-tls
  backend:
    serviceName: appserver-dev
    servicePort: 80
