registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/tls.crt 
    REGISTRY_HTTP_TLS_KEY: /certs/tls.key 
    REGISTRY_AUTH: htpasswd 
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd 
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /root/docker/auth:/auth
    - /root/docker/certs:/certs
    - /root/docker/data:/var/lib/registry
