apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: docker-registry
  labels:
    app: registry
spec:
  volumes:
    - name: registry-storage
      persistentVolumeClaim: 
        claimName: registry-pv-claim
  containers:
  - name: registry
    image: registry:2
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
    volumeMounts:
      - mountPath: /var/lib/registry
        name: registry-storage
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: docker-registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000
