apiVersion: v1
kind: ServiceAccount
metadata:
  name: rc2pgdb-sa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rc2pgdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-standard
  resources:
    requests:
        storage: 400M
---
apiVersion: v1
kind: Service
metadata:
  name: rc2pgdb
  labels:
    app: rc2pgdb
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: rc2pgdb-primary
---
apiVersion: v1
kind: Service
metadata:
  name: rc2pgdb-primary
  labels:
    app: rc2pgdb-primary
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
  selector:
    app: rc2pgdb
    rc2type: pgdb
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: rc2pgdb-replica
  labels:
    app: rc2pgdb-replica
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
  selector:
    app: rc2pgdb-replica
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: rc2pgdb
spec:
  serviceName: rc2pgdb
  selector:
    matchLabels:
      app: rc2pgdb
  replicas: 1
  template: 
    metadata:
      labels:
        app: rc2pgdb
    spec:
      serviceAccount: rc2pgdb-sa
      initContainers:
      - name: init-pgperms
        image: busybox
        command: ["sh", "-c", "chown -R 26:26 /pgdata"]
        volumeMounts:
        - name: rc2pgdata
          mountPath: /pgdata
          readOnly: false
      containers:
        - name: rc2pgdb
          image: crunchydata/crunchy-postgres-gis:centos7-10.4-1.8.3
          ports:
            - containerPort: 5432
              name: postgres
#          readinessProbe:
#            exec:
#              command:
#                - /opt/cpm/bin/readiness.sh
#            initialDelaySeconds: 40
#            timeoutSeconds: 1
#          livenessProbe:
#            exec:
#              command:
#                - /opt/cpm/bin/liveness.sh
#            initialDelaySeconds: 40
#            timeoutSeconds: 1
          env:
            - name: PGHOST
              value: /tmp
            - name: PG_MODE
              value: set
            - name: PG_PRIMARY_HOST
              value: rc2pgdb-primary
            - name: PG_REPLICA_HOST
              value: rcpgdb-replica
            - name: PG_PRIMARY_PORT
              value: "5432"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  key: PG_USER
                  name: rc2pgdb-secret
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PG_PASSWORD
                  name: rc2pgdb-secret
            - name: PG_PRIMARY_USER
              valueFrom:
                secretKeyRef:
                  key: PG_PRIMARY_USER
                  name: rc2pgdb-secret
            - name: PG_PRIMARY_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PG_PRIMARY_PASSWORD
                  name: rc2pgdb-secret
            - name: PG_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PG_ROOT_PASSWORD
                  name: rc2pgdb-secret
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  key: PG_DATABASE
                  name: rc2pgdb-secret
            - name: PGDATA_PATH_OVERRIDE
              value: rc2-data
          volumeMounts:
            - name: rc2pgdata
              mountPath: /pgdata
              readOnly: false
            - name: pgconf
              mountPath: /pgconf
              readOnly: true
      volumes:
        - name: rc2pgdata
          persistentVolumeClaim:
            claimName: rc2pgdata
        - name: pgconf
          configMap:
            name: "rc2pgdb-pgconf"
